name: Swift Unit Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run Unit Tests
        run: |
          xcodebuild \
          -scheme AnyAppTests \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
          -sdk iphonesimulator \
          clean test | xcpretty --test --color
