name: Swift Unit Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: default

    steps:

    - name: Show Xcode version
      run: xcodebuild -version

    - name: What Xcode version does this machine have

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.1.app

      
