name: Swift Unit Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: macos-latest

    steps:
      - name: Show Xcode version
        run: xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Show Xcode version
        run: xcodebuild -version
