name: Swift Unit Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: default

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
